# File: .github/workflows/set_env.yml

name: Export AWS ENV Variables

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1  # Hardcoded default or override in your environment if needed

jobs:
  export-env:
    runs-on: [self-hosted, macOS]  # Targets your Mac runner
    environment: pre-prod  # Must match the environment configured in GitHub

    steps:
    - name: Print AWS variables from environment and secrets
      run: |
        echo "Setting environment variables from GitHub Environment 'pre-prod'..."

        # Export GitHub secrets
        echo "*** AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "*** AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

        # Export GitHub environment variable
        echo "S3_BUCKET_NAME=${{ vars.S3_BUCKET_NAME }}" >> $GITHUB_ENV

        echo " ### Environment variables exported."

    - name: Verify values (debug only, don't print secrets in real workflows)
      run: |
        echo "Verify S3_BUCKET_NAME: $S3_BUCKET_NAME"
        echo "Verify AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:0:4}********"
