name: Export AWS ENV Variables

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1  # default or from repo secrets

jobs:
  export-env:
    runs-on: [self-hosted, macOS]
    environment: pre-prod

    steps:
    - name: Set and output AWS credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> $GITHUB_ENV

    - name: Print values to verify
      run: |
        echo "Access Key: $AWS_ACCESS_KEY_ID"
        echo "Bucket Name: $S3_BUCKET_NAME"
